name = "back-shop-workers"
main = "worker.js"
compatibility_date = "2026-10-01"

# KV 绑定
# namespace 名称：SEXY MINUS
# 创建时间：2026-10-01
[[kv_namespaces]]
binding = "KV"
id = "6d718f5ae2794545ac805e815cab032e"